import { StyleSheet, Dimensions } from "react-native";
import { themeColors, categories, groups } from "../Colors";

const screenWidth = Dimensions.get("window").width;
const screenHeight = Dimensions.get("window").height;

const SettingScreenStyles = StyleSheet.create({
  fullcontainer: {
    flex: 1,
  },
  setting: {
    backgroundColor: themeColors.bg,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 6,
    borderBottomColor: themeColors.highlight,
    borderBottomWidth: 1,
  },
  font: {
    flex: 1,
    fontSize: 25,
    padding: 8,
    marginVertical: 10,
    marginLeft: 10,
    color: themeColors.highlight,
  },
  information: {
    flexDirection: "row",
    justifyContent: "flex-start",
    width: "auto",
    height: "auto",
    backgroundColor: themeColors.bg,
    borderBottomColor: themeColors.highlight,
    borderBottomWidth: 1,
  },
  leftpannel: {
    justifyContent: "flex-first",
    alignItems: "center",
    paddingVertical: 7,
    paddingHorizontal: 10,
  },
  rightpannel: {
    flex: 1,
    justifyContent: "center",
    alignItems: "flex-start",
    paddingVertical: 7,
    paddingHorizontal: 10,
  },
  inputRow: {
    marginVertical: 5,
    width: "100%",
  },
  label: {
    fontSize: 16,
    marginVertical: 2,
    fontWeight: "bold",
    color: themeColors.highlight,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomColor: themeColors.highlight,
    borderBottomWidth: 1,
    marginBottom: 10,
  },
  input: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginVertical: 5,
    fontSize: 16,
    flex: 1,
    color: themeColors.highlight,
  },
  icon: {
    width: 24,
    height: 24,
    margin: 5,
    resizeMode: "contain",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    backgroundColor: themeColors.bg,
    borderRadius: 8,
    padding: 20,
    width: "95%",
    height: "auto",
  },
  modalHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottomColor: themeColors.highlight,
    borderBottomWidth: 2,
    marginBottom: 5,
  },
  modalTitle: {
    fontSize: 20,
    color: themeColors.highlight,
    marginVertical: 5,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 5,
  },
  actionButton: {
    width: "25%",
    backgroundColor: themeColors.highlight,
    borderRadius: 10,
    padding: 12,
    alignItems: "center",
  },
  cancelButton: {
    width: "25%",
    backgroundColor: themeColors.sunday,
    borderRadius: 10,
    padding: 12,
    alignItems: "center",
  },
  actionButtonText: {
    color: "white",
    fontWeight: "bold",
  },
  modalLabel: {
    fontSize: 16,
    marginVertical: 2,
    color: themeColors.highlight,
  },
  modalInput: {
    paddingHorizontal: 5,
    marginVertical: 5,
    fontSize: 16,
    flex: 1,
    color: themeColors.highlight,
  },
  labelContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 7,
  },
  categoryLabel: {
    flex: 1,
    fontSize: 16,
    fontWeight: "bold",
    color: themeColors.highlight,
  },
  categoryModalLabel: {
    fontSize: 16,
    marginTop: 5,
    color: themeColors.highlight,
    paddingBottom: 5,
  },
  categoryContainer: {
    backgroundColor: "#fff",
    flexDirection: "column",
    width: "100%",
    borderRadius: 10,
    paddingHorizontal: 5,
  },
  categoryItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 5,
    borderRadius: 7,
    marginTop: 5,
  },
  categoryText: {
    flex: 1,
    fontSize: 16,
    color: themeColors.highlight,
    marginVertical: 4,
  },
  selectedColor: {
    width: 25, 
    height: 25,
    borderRadius: 25,
    borderColor: themeColors.highlight,
    borderWidth: 2,
  },
  addCategoryButton: {
    padding: 2,
    alignItems: "center",
  },
  addIcon: {
    width: 20,
    height: 20,
    marginHorizontal: 5,
    resizeMode: "contain",
  },
  categoryModalInput: {
    paddingHorizontal: 5,
    paddingBottom: 5,
    marginVertical: 5,
    fontSize: 16,
    color: themeColors.highlight,
    borderBottomColor: themeColors.highlight,
    borderBottomWidth: 1,
  },
  checkIcon: {
    width: 24,
    height: 24,
    margin: 5,
    resizeMode: "contain",
    tintColor: "#739A6D",
  },
  colorGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginVertical: 10,
  },
  colorCircleWrapper: {
    margin: 5,
    borderRadius: 25,
  },
  colorCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginHorizontal: 10,
    justifyContent: "center",
    alignItems: "center",
    borderColor: themeColors.highlight,
    borderWidth: 2,
  },
  checkMark: {
    width: 24,
    height: 24,
    tintColor: themeColors.highlight,
  },
  findPWFont: {
    flex: 1,
    fontSize: 16,
    color: themeColors.highlight,
    marginVertical: 10,
    textAlign: "center",
  },
  lockIcon: {
    width: 28,
    height: 28,
    marginHorizontal: 5,
    marginVertical: 10,
    resizeMode: "contain",
    tintColor: themeColors.highlight, 
  },
  outText: {
    flex: 1,
    fontSize: 16,
    color: "#CB3D24",
    marginVertical: 10,
    textAlign: "center",
  },
  outIcon: {
    width: 24,
    height: 24,
    marginHorizontal: 5,
    marginVertical: 10,
    resizeMode: "contain",
    tintColor: "#CB3D24",
  }
});

export default SettingScreenStyles;
